---
- hosts: all
  become: true
  gather_facts: yes
  tasks:
    - name: Install nginx
      yum:
        name: nginx
        state: present
    - name: Copy nginx configuration for wordpress
      template:
        src: default.conf
        dest: /etc/nginx/conf.d/default.conf
        notify: restart nginx
